config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  get 'pages/batman'
  get 'pages/superman'
  get 'pages/batman_vs_superman'
  post 'pages/save_batmanfan'
  post 'pages/save_supermanfan'
  get 'pages/count_batmanfans'
  root 'pages#batman_vs_superman'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/votosbatman.rb
class Votosbatman < ApplicationRecord
end

app/models/votossuperman.rb
class Votossuperman < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def page1
  end

  def page2
      # render :layout => 'bootstrap'
      render layout: "bootstrap"
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def batman
  end

  def superman
  end

  def batman_vs_superman
    # @name_batman = params[:name_batman]
    # @email_batman = params[:email_batman]
    # @votosbatman = Votosbatman.new(name:@name_batman, email:@email_superman)
    # @votosbatman.save
    #
    # @name_superman = params[:name_superman]
    # @email_superman = params[:email_superman]
    # @votossuperman = Votossuperman.new(name:@name_superman, email:@email_superman)
    # @votossuperman.save
    @totalbatman = Votosbatman.count
    @totalsuperman = Votossuperman.count
  end

  def save_batmanfan
  Votosbatman.create(name: params[:name_batman], email: params[:email_batman])
  redirect_to pages_batman_vs_superman_path, notice: "Your vote for Batman was registered correctly."
  end

  def save_supermanfan
  Votossuperman.create(name: params[:name_superman], email: [:email_superman])
    redirect_to pages_batman_vs_superman_path, notice: "Your vote for Superman was registered correctly."
  end

  # def count_batmanfans
  # @batmanfans = Votosbatman.all
  # @total_batmanfans = @batmanfans.count
  # end
  #
  # def count_batmanfans
  # @supermanfans = Votossuperman.all
  # @total_supermanfans = @supermanfans.count
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/page1.html.erb
<!-- <h1>Experiments#page1</h1>
<p>Find me in app/views/experiments/page1.html.erb</p> -->
  <img src="<%= asset_path 'batmanvssuperman_pic.jpg' %>" alt="">

app/views/experiments/page2.html.erb
<h1>Experiments#page2</h1>
<p>Find me in app/views/experiments/page2.html.erb</p>

app/views/experiments/page3.html.erb
<h1>Experiments#page3</h1>
<p>Find me in app/views/experiments/page3.html.erb</p>

<body class="experiments page3">

</body>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <title></title>
  </head>

  <body>


    <nav class="navbar navbar-default">
      <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Brand</a>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
          <li><a href="#">Link</a></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    <!-- <%= yield%> -->
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes2</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags%>

    <!-- <script>
    body {
        // background-image: url("<%= asset_path 'batmanvssuperman_pic' %>");
        background-image: url(batmanvssuperman_pic.jpg);
        background-color:red;
    }
    </script> -->

  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <meta charset="utf-8">
    <title></title>
  </head>

  <body>
    <%=render 'layouts/navbar' %>
    <%= yield%>
  </body>
</html>

app/views/pages/batman.html.erb
<!-- <h1>Pages#batman</h1>
<p>Find me in app/views/pages/batman.html.erb</p>
<p>hello</p> -->

<h1 style= "font-size:50px; color:white; font-family: helvetica";> I am batman </h1>

<body>
  <!-- <img src="<%= asset_path 'batman_pic' %>"> -->
</body>


<!-- <script>
  $.backstretch("<%= asset_path 'batman_pic' %>");
</script> -->

<!-- <script>
  $.backstretch(<%= image_tag 'batman_pic.jpg' %>);
</script> -->

<script>
  $.backstretch("<%= asset_path 'batman_pic.jpg' %>");
</script>

app/views/pages/batman_vs_superman.html.erb
<!-- <h1>Pages#batman</h1>
<p>Find me in app/views/pages/batman.html.erb</p>
<p>hello</p> -->
<style>
.size-image {
    width: 100%;
    height: 100%;
    display: inline-block;
}
.container {
font-size:0}

.container2 {
  padding-top: 15px;
  width: 100%;
  display: inline-table;
  display: inline-table;
  text-align: center;
  font-family: sans-serif;
  color:white;
  background-color: black;
}
.column {
display: inline-block;
width: 50%;
}

.pregunta{
  text-align: center;
  font-family: sans-serif;
  color:white;
  font-size: 60;
}
</style>

<body>
<div class="container">
  <div class="column">
    <a href="<%= pages_batman_url %>">
    <img border="0" alt="Batman" src="<%= asset_path 'batman_pic.jpg' %>" class="size-image">
    </a>
  </div>

  <div class="column">
    <a href="<%= pages_superman_url %>">
    <img border="0" alt="Batman" src="<%= asset_path 'superman_pic.jpg' %>" class="size-image">
    </a>
  </div>
</div>

<div class="container2">
  <div>
    <p class:"pregunta">Who's going to win?</p>
  </div>
  <div class="column">
    <form action = "<%= pages_save_batmanfan_path %>" method="POST">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <input type="text" name="name_Batman" value="">
      <input type="text" name="email_Batman" value="">
      <input type="submit" name="Send" value="Send">
    </form>
    <br>
    <!-- <p1>Votos para Batman: <%= Votosbatman.count %> </p1> -->
    <p1><%= @totalbatman %> votes for Batman</p1>

  </div>

  <div class="column">
    <form action = "<%= pages_save_supermanfan_path %>" method="POST">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <input type="text" name="name_Superman" value="">
      <input type="text" name="email_Superman" value="">
      <input type="submit" name="Send" value="Send">
    </form>
    <br>
    <!-- <p1>Votos para Superman: <%= Votossuperman.count %> </p1> -->
    <p1><%= @totalsuperman %> votes for Superman</p1>
  </div

</div>

<p style="color:green, text-align:center; font-family:helvetica"> <%= flash[:notice] %> </p>

</body>

app/views/pages/superman.html.erb
<!-- <h1>Pages#batman</h1>
<p>Find me in app/views/pages/batman.html.erb</p>
<p>hello</p> -->

<h1 style= "font-size:50px; color:white; font-family: helvetica; text-align: right";> This looks like a job for Superman  </h1>


<body>
  <!-- <img src="<%= asset_path 'batman_pic' %>"> -->
</body>


<script>
  $.backstretch("<%= asset_path 'superman_pic.jpg' %>");
</script>